In [1]:
import numpy as np 


In [2]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [3]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # No need to do transpose
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


In [4]:
layer1=Layer_Dense(4,6)
layer2=Layer_Dense(6,3)

In [5]:
layer1.forward(X)
print(layer1.output)

[[ 0.67300116 -0.16727715 -0.42785846  0.56971597  0.87989728 -0.05396182]
 [ 0.81436445 -0.17863381 -0.41084612  0.75083418  0.46901272  0.403764  ]
 [ 0.21801305  0.00759039  0.17603426 -0.16744934  0.18264926  0.5309165 ]]


In [6]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.14629144 -0.04806473 -0.00102545]
 [ 0.07858986 -0.17342173 -0.04980909]
 [ 0.09165886 -0.05176894 -0.09859882]]
